export const db = [
	{
		"id": 1,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"home-1",
	},
	{
		"id": 2,
		"type":"House",
		"price":"67000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"3",
		"area":"195",
		"image":"home-2",
	},
	{
		"id": 3,
		"type":"Condo",
		"price":"28000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"2",
		"area":"195",
		"image":"home-3",
	},
	{
		"id": 4,
		"type":"House",
		"price":"46000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"4",
		"area":"195",
		"image":"home-4",
	},
	{
		"id": 5,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"home-5",
	},
	{
		"id": 6,
		"type":"House",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"3",
		"area":"195",
		"image":"home-6",
	},
	{
		"id": 7,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"home-7",
	},
	{
		"id": 8,
		"type":"House",
		"price":"77000",
		"des":"Nice place, view is really good!",
		"bedrooms":"5",
		"bathrooms":"5",
		"area":"395",
		"image":"home-8",
	},
	{
		"id": 9,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"home-9",
	}
];