export const db = [
	{
		"id": 1,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"../src/assets/Images/home-1.jpg",
	},
	{
		"id": 2,
		"type":"House",
		"price":"67000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"3",
		"area":"195",
		"image":"../src/assets/Images/home-2.jpg",
	},
	{
		"id": 3,
		"type":"Condo",
		"price":"28000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"2",
		"area":"195",
		"image":"../src/assets/Images/home-3.jpg",
	},
	{
		"id": 4,
		"type":"House",
		"price":"46000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"4",
		"area":"195",
		"image":"../src/assets/Images/home-4.jpg",
	},
	{
		"id": 5,
		"type":"Condo",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"2",
		"bathrooms":"1.5",
		"area":"195",
		"image":"../src/assets/Images/home-5.jpg",
	},
	{
		"id": 6,
		"type":"House",
		"price":"26000",
		"des":"Nice place, view is really good!",
		"bedrooms":"4",
		"bathrooms":"3",
		"area":"195",
		"image":"../src/assets/Images/home-6.jpg",
	}
];